### PR TITLE
add support for Aliyun images

### PR DESCRIPTION
**Pull request by miabbott**
This adds support for images uploaded to the Aliyun cloud.

Mostly a copy/paste of the existing AWS types and methods.

Closes: #29

### CODE REVIEW

**Comment by miabbott** [comment]
I imagine there is a better way to handle the similarities between AWS + Aliyun, but my Go isn't that great these days, so I brute forced it

**Comment by miabbott** [comment]
(Marked as Draft in case there is a better solution that should be pursued)

**Comment by cgwalters** [comment]
cc @bgilbert who may have opinions

**Review by bgilbert — APPROVED** [review]
LGTM!

**Review by cgwalters — APPROVED** [review]
Nice work!

**Comment by cgwalters** [comment]
Next step is a PR to bump this vendored version in coreos-assembler btw.

**Pull request merged**
